### ISSUE TITLE
Missing transf_matrices_all_seqs.pkl

### ISSUE THREAD

**Issue by L-Scofano** [sanweiliti/EgoHMR#2]
Hello and thanks for the great work! I'm trying to run training code, however I can't seem to locate the file named "transf_matrices_all_seqs.pkl." 
Could it be that I missed a step somewhere, or is it possible that the file hasn't been included? Your help would be greatly appreciated!

**Comment by sanweiliti** [comment]
Hello,
This file is updated and you should be able to find it in the download link now.
